{
    'name': 'CPO eCommerce',
    'category': 'Website',
    'sequence': 56,
    'summary': 'Sell Your PCB Online',
    'website': 'https://www.chinapcbone.com/',
    'version': '1.0',
    'description': """
CPO E-Commerce
==================

        """,
    'depends': ['website_sale', 'document',
                'cpo_offer_base', 'website_cpo_advertising',
                'sale_pcb_rfq', 'website_cpo_index', 'website_cpo_seo',
                # 'cpo_preferential', 'message_system', 'cpo_sale_allocations',
                'cpo_login',
                ],
    'data': [
		'security/website_cpo_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        # 'data/cpo_website_demo_data.xml',
        # 'data/web_planner_data.xml',
        # 'views/product_views.xml',
        # 'views/account_views.xml',
        # 'views/sale_report_views.xml',
        # 'views/sale_order_views.xml',
        # 'views/crm_team_views.xml',
        # 'views/template_cpo_website_demo.xml',
        'views/templates_index.xml',
        'views/cpo_banner_template.xml',
        'views/cpo_index_content_template.xml',
        'views/templates.xml',
        'views/pcb_quotation_temp.xml',
        'views/pcba_quotation_temp.xml',
        'views/cpo_stencil_quotation_template.xml',
        'views/cpo_service.xml',
        'views/website_sale.xml',
        'views/website_sale_cart.xml',
        'views/cpo_my_account.xml',
        'views/cpo_login_and_signup.xml',
        'views/cpo_help.xml',
        'views/sale_order_express.xml',
        'views/cpo_inherit_sale_order_views.xml',
        'views/im_livechat.xml',
        'views/special_process/cpo_pcb_package_price_template.xml',
        'views/special_process/cpo_hdi_page_template.xml',
        'views/special_process/cpo_flexible_pcbs_template.xml',
        'views/special_process/cpo_pcba_package_price_template.xml',
        # 'views/payment_views.xml',
        # 'views/snippets.xml',
        # 'views/report_shop_saleorder.xml',
        # 'views/res_config_view.xml',
    ],
    # 'demo': [
    #     'data/demo.xml',
    # ],
    'qweb': ['static/src/xml/*.xml'],
    'installable': True,
    'application': True,
}
